# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'Paciente' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'


  # Pods for Paciente

  target 'PacienteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PacienteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
